## Importing Modules

In [53]:
import pandas as pd 
import numpy as np 
import psycopg2 
from sqlalchemy import create_engine

## Reading CSV File

In [30]:
df = pd.read_csv("HR_Analytics-4.csv")
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,VK4120,60,55+,No,Travel_Rarely,422,Operations,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,VK4280,60,55+,No,Travel-Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,VK5370,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,VK8800,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,VK12100,60,55+,No,Travel_Rarely,370,Operations,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

## EDA (Exploratory Data Analysis)

In [31]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [32]:
df.tail()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
1475,VK4120,60,55+,No,Travel_Rarely,422,Operations,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,VK4280,60,55+,No,Travel-Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,VK5370,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,VK8800,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,VK12100,60,55+,No,Travel_Rarely,370,Operations,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [33]:
df.describe()

,Age,DailyRate,DistanceFromHome(KM),Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
count,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,...,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1419.000000
mean,36.936486,801.189865,9.235811,2.910811,1.0,1034.501351,2.724324,2.731081,2.064865,2.720270,...,2.706081,80.0,0.789865,11.281757,2.796622,2.758784,7.010135,4.224324,2.180405,4.113460
std,9.092494,403.291325,8.125566,1.023796,0.0,606.778390,1.093197,0.711620,1.105574,1.103253,...,1.083138,0.0,0.849630,7.771479,1.289103,0.707769,6.116342,3.616273,3.219577,3.556786
min,19.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,494.750000,2.000000,2.000000,1.000000,2.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1029.500000,3.000000,3.000000,2.000000,3.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1573.250000,4.000000,3.000000,3.000000,4.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,4.000000,5.000000,4.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [34]:
df.isna().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome(KM)         0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
HourlyRate                   0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
SalaryHike %                 0
PerformanceRating            0
RelationshipSatisfaction     0
StandardWorkingHours         0
StockOptionLevel             0
TotalExperience(Years)       0
TrainingsLastYear            0
WorkLifeBalance              0
YearsatCompany               0
YearsinCurrentRole           0
YearsSincePromotion          0
YearsWithCurrManager        61
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(2)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome(KM)      1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  JobInvolvement            1480 non-null   int64
 15  JobLevel                  1480 non-null   int64
 16  JobRole                   1480 non-null   object
 17  JobSatisfaction           1480 non-null   int64
 18  MaritalStatus             1480 non-null   object
 19  MonthlyIncome             1480 non-null   int64
 20  SalarySlab                1480 non-null   object
 21  HourlyRate                1480 non-null   float64
 22  NumCompaniesWorked        1480 non-null   int64
 23  Over18                    1480 non-null   object
 24  OverTime                  1480 non-null   object
 25  SalaryHike %              1480 non-null   int64
 26  PerformanceRating         1480 non-null   int64
 27  RelationshipSatisfaction  1480 non-null   int64
 28  StandardWorkingHours      1480 non-null   int64
 29  StockOptionLevel          1480 non-null   int64
 30  TotalExperience(Years)    1480 non-null   int64
 31  TrainingsLastYear         1480 non-null   int64
 32  WorkLifeBalance           1480 non-null   int64
 33  YearsatCompany            1480 non-null   int64
 34  YearsinCurrentRole        1480 non-null   int64
 35  YearsSincePromotion       1480 non-null   int64
 36  YearsWithCurrManager      1419 non-null   float64
dtypes: float64(2), int64(23), object(12)
memory usage: 427.9+ KB

In [37]:
df.dtypes

EmpID                        object
Age                           int64
AgeGroup                     object
Attrition                    object
BusinessTravel               object
DailyRate                     int64
Department                   object
DistanceFromHome(KM)          int64
Education                     int64
EducationField               object
EmployeeCount                 int64
EmployeeNumber                int64
EnvironmentSatisfaction       int64
Gender                       object
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                 int64
SalarySlab                   object
HourlyRate                  float64
NumCompaniesWorked            int64
Over18                       object
OverTime                     object
SalaryHike %                  int64
PerformanceRating             int64
RelationshipSatisfaction      int64
StandardWorkingHours          int64
StockOptionLevel              int64
TotalExperience(Years)        int64
TrainingsLastYear             int64
WorkLifeBalance               int64
YearsatCompany                int64
YearsinCurrentRole            int64
YearsSincePromotion           int64
YearsWithCurrManager        float64
dtype: object

In [38]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome(KM)', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'SalarySlab', 'HourlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'SalaryHike %',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardWorkingHours',
       'StockOptionLevel', 'TotalExperience(Years)', 'TrainingsLastYear',
       'WorkLifeBalance', 'YearsatCompany', 'YearsinCurrentRole',
       'YearsSincePromotion', 'YearsWithCurrManager'],
      dtype='object')

### 1. Basic Statistics — Age

In [39]:
age = df['Age'].to_numpy()
income = df['MonthlyIncome'].to_numpy()
daily_rate = df['DailyRate'].to_numpy()
experience = df['TotalExperience(Years)'].to_numpy()
companies = df['NumCompaniesWorked'].to_numpy()

print("Mean Age:", np.mean(age))
print("Median Age:", np.median(age))
print("Minimum Age:", np.min(age))
print("Maximum Age:", np.max(age))
print("Standard Deviation:", np.std(age))

Mean Age: 36.93648648648649
Median Age: 36.0
Minimum Age: 19
Maximum Age: 60
Standard Deviation: 9.089421744820887

### 2. Check Missing Values

In [40]:
print("Missing Age:", np.sum(np.isnan(age)))
print("Missing Income:", np.sum(np.isnan(income)))

Missing Age: 0
Missing Income: 0

##  3. Monthly Income Analysis

In [41]:
print("Mean Income:", np.mean(income))
print("Median Income:", np.median(income))
print("Minimum Income:", np.min(income))
print("Maximum Income:", np.max(income))

Mean Income: 49511.31689189189
Median Income: 49651.0
Minimum Income: 1055
Maximum Income: 99806

### 4. Experience Analysis

In [42]:
print("Average Experience:", np.mean(experience))
print("Minimum Experience:", np.min(experience))
print("Maximum Experience:", np.max(experience))

Average Experience: 11.281756756756756
Minimum Experience: 0
Maximum Experience: 40

### 5. Find Employees with High Income

In [43]:
high_income = income[income > np.mean(income)]
print("Number of employees earning above average:",len(high_income))

Number of employees earning above average: 741

### 6. Find Possible Outliers in Monthly Income

In [44]:
Q1 = np.percentile(income, 25)
Q3 = np.percentile(income, 75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = income[(income < lower_limit) | (income > upper_limit)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Number of outliers:", len(outliers))

Q1: 24371.5
Q3: 74512.5
IQR: 50141.0
Number of outliers: 0

### 7. NumPy Conditional Analysis

In [45]:
older_employees = age[age > 40]
print("Employees older than 40:", len(older_employees))
experienced = experience[experience > 5]
print("Employees with more than 5 years experience:",len(experienced))

Employees older than 40: 467
Employees with more than 5 years experience: 1163

### 8. Correlation Between Age and Income

In [46]:
correlation = np.corrcoef(age, income)[0, 1]
print("Correlation between Age and Income:", correlation)

Correlation between Age and Income: -0.037519289445228136

In [47]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

## Cleaning and Transforming Data

In [48]:
df["YearsWithCurrManager"] = df["YearsWithCurrManager"].fillna("0")

In [49]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome(KM)', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'SalarySlab', 'HourlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'SalaryHike %',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardWorkingHours',
       'StockOptionLevel', 'TotalExperience(Years)', 'TrainingsLastYear',
       'WorkLifeBalance', 'YearsatCompany', 'YearsinCurrentRole',
       'YearsSincePromotion', 'YearsWithCurrManager'],
      dtype='object')

In [54]:
def experience_group(years):
    if years < 2:
        return "Fresher"
    elif years < 5:
        return "Junior"
    elif years < 10:
        return "Mid-Level"
    elif years < 20:
        return "Senior"
    else:
        return "Expert"
df["ExperienceGroup"] = df["TotalExperience(Years)"].apply(experience_group)

In [56]:
def age_category(age):
    if age < 25:
        return "Young"
    elif age < 35:
        return "Adult"
    elif age < 50:
        return "Middle Age"
    else:
        return "Senior"

df["AgeCategory"] = df["Age"].apply(age_category)

In [57]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager,ExperienceGroup,AgeCategory
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,0,0,2,3,0,0,0,0.0,Fresher,Young
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,0,2,3,0,0,0,0.0,Fresher,Young
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,0,0,3,3,0,0,0,0.0,Fresher,Young
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,0,0,2,3,0,0,0,0.0,Fresher,Young
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,0,0,0,3,0,0,0,0.0,Fresher,Young

## Exporting Data Into CSV

In [58]:
df.to_csv("HR_Analytics.csv",index=False)

## Exporting Data To SQL

In [59]:
connection = psycopg2.connect(
    host="localhost",
    port="5432",
    database="hr_analytics_business_insights",
    user="postgres",
    password="1234"
)
engine = create_engine( "postgresql+psycopg2://postgres:1234@localhost:5432/hr_analytics_business_insights")

In [60]:
cursor = connection.cursor()
cursor.execute("SELECT version();")

In [63]:
df.to_sql(
    name= "Business_Questions",
    con=engine,
    if_exists="replace",
    index=False)

642

In [65]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager,ExperienceGroup,AgeCategory
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,0,0,2,3,0,0,0,0.0,Fresher,Young
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,0,2,3,0,0,0,0.0,Fresher,Young
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,0,0,3,3,0,0,0,0.0,Fresher,Young
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,0,0,2,3,0,0,0,0.0,Fresher,Young
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,0,0,0,3,0,0,0,0.0,Fresher,Young