In [25]:
import pandas as pd

In [26]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [27]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [29]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [30]:
df.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)     float64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Previous Purchases        float64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [31]:
df.size

85850

In [32]:
df.shape

(5050, 17)

In [33]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

## Cleaning

In [34]:
df["Purchase Amount (USD)"] = df["Purchase Amount (USD)"].fillna(df["Purchase Amount (USD)"].mean())

In [35]:
df["Review Rating"] = df["Review Rating"].fillna(df["Review Rating"].mean())

In [36]:
df["Previous Purchases"] = df["Previous Purchases"].fillna(df["Previous Purchases"].median())

In [51]:
df["size"] = df["size"].fillna("Unknown")

In [52]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_(usd)     0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [38]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [39]:
df["Previous Purchases"] = df["Previous Purchases"].astype(int)

In [40]:
df["Purchase Amount (USD)"] = df["Purchase Amount (USD)"].astype(int)

In [41]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68,California,XL,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly

In [42]:
df.columns = df.columns.str.replace(" ","_")
df.columns = df.columns.str.lower()

In [43]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [45]:
df["review_rating"] = df["review_rating"].round(1)

In [46]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68,California,XL,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly

In [54]:
df.to_csv("Customer_Behavior.csv",index = False)